# Generated by Django 5.1.3 on 2024-12-12 03:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0003_alter_customuser_age_alter_customuser_weight"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="caloric_intake",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="customuser",
            name="height_FT",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="customuser",
            name="height_IN",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="customuser",
            name="fitness_level",
            field=models.CharField(
                choices=[
                    ("Inactive", "Inactive"),
                    ("Low Active", "Low Active"),
                    ("Active", "Active"),
                    ("Very Active", "Very Active"),
                ],
                max_length=11,
            ),
        ),
        migrations.AlterField(
            model_name="customuser",
            name="gender",
            field=models.CharField(
                choices=[("male", "Male"), ("female", "Female")], max_length=6
            ),
        ),
    ]
