# Generated by Django 5.0.8 on 2024-12-11 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_customuser_age_alter_customuser_weight'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='caloric_intake',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
