# Generated by Django 5.1.3 on 2024-12-11 23:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0004_customuser_caloric_intake"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="height",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="customuser",
            name="fitness_level",
            field=models.IntegerField(
                choices=[
                    (1, "Inactive"),
                    (2, "Low Active"),
                    (3, "Active"),
                    (4, "Very Active"),
                ]
            ),
        ),
    ]
