# Generated by Django 5.1.3 on 2024-12-12 00:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0005_customuser_height_alter_customuser_fitness_level"),
    ]

    operations = [
        migrations.RenameField(
            model_name="customuser",
            old_name="height",
            new_name="height_ft",
        ),
        migrations.AddField(
            model_name="customuser",
            name="height_in",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
