# Generated by Django 5.1.3 on 2024-12-12 00:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0006_rename_height_customuser_height_ft_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="dailycheckin",
            name="date",
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
