# Generated by Django 5.1.3 on 2024-12-12 01:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0007_alter_dailycheckin_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="fitness_level",
            field=models.CharField(
                choices=[
                    ("Inactive", "Inactive"),
                    ("Low Active", "Low Active"),
                    ("Active", "Active"),
                    ("Very Active", "Very Active"),
                ],
                max_length=11,
            ),
        ),
        migrations.AlterField(
            model_name="customuser",
            name="gender",
            field=models.CharField(
                choices=[("Male", "Male"), ("Female", "Female")], max_length=6
            ),
        ),
    ]
