# Generated by Django 5.0.8 on 2024-12-05 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nutrition', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='food',
            name='serving_size',
            field=models.CharField(max_length=50),
        ),
    ]
