# Generated by Django 5.1.3 on 2024-12-12 00:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("nutrition", "0002_alter_food_serving_size"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="food",
            name="date",
            field=models.DateField(default="2024-01-01"),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="food",
            name="name",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
