# Generated by Django 5.1.3 on 2024-12-12 00:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("nutrition", "0003_food_date_alter_food_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="food",
            name="date",
            field=models.DateField(null=True),
        ),
    ]
