# Generated by Django 5.1.3 on 2024-12-12 00:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("nutrition", "0004_alter_food_date"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="food",
            name="date",
        ),
    ]
