# Generated by Django 5.1.3 on 2024-12-12 00:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("nutrition", "0005_remove_food_date"),
    ]

    operations = [
        migrations.AddField(
            model_name="food",
            name="date",
            field=models.DateField(null=True),
        ),
    ]
