# Generated by Django 5.1.3 on 2024-12-12 03:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("nutrition", "0008_food_date_alter_food_name"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="food",
            name="serving_size",
        ),
    ]
