# Generated by Django 5.1.3 on 2024-12-12 03:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("nutrition", "0009_remove_food_serving_size"),
    ]

    operations = [
        migrations.AlterField(
            model_name="food",
            name="date",
            field=models.DateField(null="01-01-2024"),
        ),
    ]
