# Generated by Django 5.1.3 on 2024-11-21 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("workouts", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="liftingworkout",
            name="weight",
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
