# Generated by Django 5.1.3 on 2024-11-21 18:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("workouts", "0002_liftingworkout_weight"),
    ]

    operations = [
        migrations.RenameField(
            model_name="cardioworkout",
            old_name="user",
            new_name="name",
        ),
        migrations.RenameField(
            model_name="liftingworkout",
            old_name="user",
            new_name="name",
        ),
    ]
